Added pseudo price
shopware5/SwagUserPrice pull request #1
Opened 2016-12-27 09:53 UTC by LiaraAlis

With this changes it would be possible to save pseudo prices for customer related prices.
The pseudo price will be displayed in the frontend.

Please merge them and publish it with one of the next releases.

Please ask me for questions or if there are any problems with these changes.

2016-12-27 09:58 UTC, mitelg requested changes

2016-12-27 09:58 UTC, mitelg commented on Snippets/backend/plugins/user_price/view/prices.ini
> +prices/header/pseudoPrice = "Price"
please rename this snippet

2016-12-27 09:58 UTC, mitelg commented on Bootstrap/Setup.php
> +              `pseudoPrice` DOUBLE DEFAULT '0',
please also consider the new column of the table in case of updating the plugin.

2016-12-27 10:01 UTC, mitelg commented
Hey @LiaraAlis thanks for your PR :+1: 
please have a look at my comments :wink: 
It also seems that your branch is out-dated. please rebase your branch to the current master

2016-12-27 10:09 UTC, LiaraAlis commented on Bootstrap/Setup.php
> +              `pseudoPrice` DOUBLE DEFAULT '0',
Oh, you're right. I've not considered this. 🤣

2016-12-27 10:24 UTC, LiaraAlis commented on Bootstrap/Setup.php
> +              `pseudoPrice` DOUBLE DEFAULT '0',
Changes done. Hope they are okay. I have forked the repository today, so I can not see that my branch is out-dated.

2016-12-27 10:24 UTC, LiaraAlis commented
Changes done. Hope they are okay. I have forked the repository today, so I can not see that my branch is out-dated.

2016-12-27 11:39 UTC, LiaraAlis reviewed
Changes done. Hope they are okay. I have forked the repository today, so I can not see that my branch is out-dated.

2016-12-27 11:59 UTC, ghost approved these changes

2016-12-27 12:06 UTC, bpanet commented on Bootstrap/Setup.php
> +              `pseudoPrice` DOUBLE DEFAULT '0',
A helper method for this is implemented now.

2016-12-27 12:42 UTC, mitelg commented
hey @LiaraAlis thanks for your changes, but unfortunately the sync with our interal repo was not working correctly. sorry for the inconvenience! could you please rebase your branch now?

2016-12-27 12:46 UTC, mitelg requested changes

2016-12-27 12:46 UTC, mitelg commented on Bootstrap/Setup.php
> +        if (version_compare($oldVersion, '2.1.1', '<')) {
please use `version_compare($oldVersion, '2.1.1', '<=')` because the next version will be 2.1.2

2016-12-27 14:18 UTC, LiaraAlis commented on Bootstrap/Setup.php
> +        if (version_compare($oldVersion, '2.1.1', '<')) {
Oh, I did not pay attention. Sorry. :(

2016-12-27 14:19 UTC, LiaraAlis reviewed
Oh, I did not pay attention of the version number. Sorry. :(

2016-12-27 14:33 UTC, LiaraAlis commented
I've updated my branch to the current master.

2016-12-27 14:41 UTC, mitelg approved these changes

2017-09-14 12:05 UTC, LiaraAlis commented
Any news here? It would be nice if this feature would be added very soon.

2017-09-14 12:41 UTC, mitelg commented
hi @LiaraAlis 
as this plugin is not officially supported by us anymore, the ticket has not a high priority in our workflow. but I will have a look, if I could push it a little bit :wink:

2022-02-16 15:59 UTC, mitelg commented
hey @LiaraAlis 

Sorry for the late answer!
The corresponding ticket was closed. If this change is still relevant for you, please feel free to create a new PR.

2022-02-16 15:59 UTC, closed without merging